substitutions:
  # Modify variables based on your settings
  hostname: 'esp_03'
esphome:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2

<<: !include common.yaml

# Sensors bellow
text_sensor:
  - platform: version
    name: $hostname version
  - platform: wifi_info
    ip_address:
      name: $hostname IP Address
      icon: mdi:ip-network
    bssid:
      name: $hostname Connected BSSID
      icon: mdi:identifier
binary_sensor:
  - platform: status
    name: $hostname Status
#  - platform: gpio
#    pin: D6
#    name: $hostname PIR Sensor
#    device_class: motion
sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal Sensor
    update_interval: 3600s
  - platform: dht
    pin: D4
    model: DHT22
    update_interval: 300s
    temperature:
      name: $hostname Temperature
      unit_of_measurement: '°C'
      icon: "mdi:thermometer"
      accuracy_decimals: 1
    humidity:
      name: $hostname Humidity
      unit_of_measurement: '%'
      icon: "mdi:water-percent"
switch:
  - platform: restart
    name: $hostname restart
