substitutions:
# Sonoff T1 2CH Module
  hostname: 'sonoff_01'
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: True
  ap:
    ssid: $hostname
  
api:
  reboot_timeout: 0s
  password: !secret apipass
ota:
  safe_mode: True
  password: !secret otapass

logger: 

# Sensors
text_sensor:
  - platform: version
    name: $hostname version
sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal Sensor
    update_interval: 3600s
binary_sensor:
  - platform: status
    name: $hostname Status
# SonOff T2 2CH configuration
  - platform: gpio
    pin:
     number: GPIO0
     mode: INPUT_PULLUP
     inverted: True
    name: "$hostname Button 1"
    on_press:
      - light.toggle: lightsw_01
  - platform: gpio
    pin:
     number: GPIO9
     mode: INPUT_PULLUP
     inverted: True
    name: "$hostname Button 2"
    on_press:
      - light.toggle: lightsw_02
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
  - platform: esp8266_pwm
    id: sonoff_led
    pin:
      number: GPIO13
      inverted: True
switch:
  - platform: restart
    name: $hostname restart
light:
  - platform: monochromatic
    name: "Sonoff LED"
    output: sonoff_led
  - platform: binary
    name: "$hostname light 1"
    id: lightsw_01
    output: relay_1
  - platform: binary
    name: "$hostname light 2"
    id: lightsw_02
    output: relay_2