substitutions:
  # Modify variables based on your settings
  hostname: 'esp_01'
esphome:
  name: $hostname
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  domain: .local
  ap:
    ssid: $hostname

logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  password: !secret apipass
ota:
  safe_mode: True
  password: !secret otapass

# Sensors bellow
text_sensor:
  - platform: version
    name: $hostname version
sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal Sensor
    update_interval: 3600s
  - platform: adc
    pin: A0
    name: $hostname CO
    accuracy_decimals: 3
    unit_of_measurement: 'ppm'
    icon: "mdi:periodic-table"
    update_interval: 300s
    
binary_sensor:
  - platform: status
    name: $hostname Status

switch:
  - platform: restart
    name: $hostname restart