substitutions:
  hostname: 'shellydimmer201'
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  fast_connect: True
captive_portal:
    
api:
  reboot_timeout: 0s
  password: !secret apipass
ota:
  safe_mode: True
  password: !secret otapass

#logger: 

# Sensors
text_sensor:
  - platform: version
    name: $hostname version
sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal Sensor
    update_interval: 3600s
#  - platform: adc
#    pin: GPIO17
#    name: "${hostname} ADC temperature"
#    update_interval: 60s
#    unit_of_measurement: "°C"
#    device_class: "temperature"

# Device Specific Config
external_components:
  - source:
      type: git
      url: https://github.com/rnauber/esphome.git
      ref: feature/shelly-dimmer
    refresh: 1min
    components: [ shelly_dimmer ]
# disable serial, we need this to talk to the co-processor
logger:
  baud_rate: 0

uart:
 tx_pin: 1
 rx_pin: 3
 baud_rate: 115200

# define a light 
light:
  - platform: shelly_dimmer
    id: ${hostname}_d1
    name: "${hostname} Dimmer 1"
    leading_edge: false
    min_brightness: 0
    max_brightness: 1000
    gamma_correct: 1
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF
    power:
      name: "${hostname} Power"
    voltage:
      name: "${hostname} Voltage"
    current:
      name: "${hostname} Current"
    
binary_sensor:
  - platform: status
    name: $hostname Status
    internal: true
  - platform: gpio
    id: "${hostname}_sw1"
    internal: true
    pin:
      number: GPIO14
    on_state:
      then:
         - light.toggle:
             id: ${hostname}_d1