substitutions:
# Sonoff T1 1CH Module
  hostname: 'sonoff_06'
  devicename: 'sonoff_06'
  ssid: !secret wifissid2
  password: !secret wifipass2
  otapass: !secret otapass
  apipass: !secret apipass
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${ssid}
  password: ${password}
  power_save_mode: HIGH # for ESP8266 LOW/HIGH are mixed up, esphome/issues/issues/1532
  manual_ip:
    static_ip: 192.168.2.17
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4
  ap:
    ssid: ${devicename}
    password: ${password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0
      dns1: 8.8.8.8
      dns2: 8.8.4.4
captive_portal:
logger:
    level: INFO
web_server:
  port: 80
api:
  reboot_timeout: 0s
  password: !secret apipass
ota:
  safe_mode: True
  password: !secret otapass

# Sensors
text_sensor:
  - platform: version
    name: $hostname version
sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal Sensor
    update_interval: 3600s
binary_sensor:
  - platform: status
    name: $hostname Status
# SonOff T2 2CH configuration
  - platform: gpio
    pin:
     number: GPIO0
     mode: INPUT_PULLUP
     inverted: True
    name: "$hostname Button 1"
    on_press:
      - light.toggle: lightsw_01

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: esp8266_pwm
    id: sonoff_led
    pin:
      number: GPIO13
      inverted: True
switch:
  - platform: restart
    name: $hostname restart
light:
  - platform: monochromatic
    name: "Sonoff LED"
    output: sonoff_led
  - platform: binary
    name: "$hostname light 1"
    id: lightsw_01
    output: relay_1